export const ROUTES = {
  home: '/',
  products: '/products',
  product: (idOrSlug: string) => `/products/${idOrSlug}`,
  category: (category: string, subCategory?: string | null) =>
    subCategory ? `/category/${category}/${subCategory}` : `/category/${category}`,
  favorites: '/favorites',
  cart: '/cart',
  checkout: '/checkout',
  login: '/login',
  register: '/register',
  account: '/account',
  accountOrders: '/account/orders',
  accountOrder: (id: string) => `/account/orders/${id}`,
  accountNotifications: '/account/notifications',
  accountMessages: '/account/messages',
  admin: '/admin',
  adminProducts: '/admin/products',
  adminProductNew: '/admin/products/new',
  adminProductEdit: (id: string) => `/admin/products/${id}/edit`,
  adminCategories: '/admin/categories',
  adminStock: '/admin/stock',
  adminOrders: '/admin/orders',
  adminOrder: (id: string) => `/admin/orders/${id}`,
  adminNotifications: '/admin/notifications',
  adminMessages: '/admin/messages',
  legal: (doc: string) => `/legal/${doc}`,
} as const;
